sudo: required
services:
  - docker

before_install: 
  - docker build -t promisemb/docker-react -f Dockerfile.dev .

script: 
   - docker run promisemb/docker-react npm run test -- --coverage

deploy: 
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "Dockerreact-env"
    bucket_name: "elasticbeanstalk-us-east-1-599782099028Info"
    bucket_path: "docker-react"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: "$AWS_SECRET_KEY"

